# imported from KiCad /tmp/hackrf-pro/praline.kicad_pcb
name = "KiCad_L_Taiyo-Yuden_A251818"
reference = "U"
description = "pins of an imported KiCad footprint"

[[bodies]]

[[bodies.left]]
number = "1"

[[bodies.right]]
number = "2"
