# imported from KiCad /tmp/hackrf-pro/praline.kicad_pcb
name = "KiCad_TSOP-6_1.65x3.05mm_P0.95mm"
reference = "U"
description = "pins of an imported KiCad footprint"

[[bodies]]

[[bodies.left]]
number = "1"

[[bodies.left]]
number = "2"

[[bodies.left]]
number = "3"

[[bodies.right]]
number = "4"

[[bodies.right]]
number = "5"

[[bodies.right]]
number = "6"
