# imported from KiCad /tmp/hackrf-pro/praline.kicad_pcb
name = "KiCad_LED_Single_Xinglight_XL-3210_Horizontal"
reference = "U"
description = "pins of an imported KiCad footprint"

[[bodies]]

[[bodies.left]]
number = "1"

[[bodies.right]]
number = "2"
