# imported from KiCad /tmp/hackrf-pro/praline.kicad_pcb
name = "KiCad_Anaren_0805_2012Metric-6"
reference = "U"
description = "pins of an imported KiCad footprint"

[[bodies]]

[[bodies.left]]
number = "1"

[[bodies.left]]
number = "2"

[[bodies.left]]
number = "3"

[[bodies.right]]
number = "4"

[[bodies.right]]
number = "5"

[[bodies.right]]
number = "6"
