# imported from KiCad Connector_Generic:Conn_02x05_Odd_Even
name = "Conn_02x05_Odd_Even"
reference = "J"
description = "Generic connector, double row, 02x05, odd/even pin numbering scheme (row 1 odd numbers, row 2 even numbers), script generated (kicad-library-utils/schlib/autogen/connector/)"
keywords = ["connector"]
footprint = "Tag-Connect_TC2050-IDC-NL_2x05_P1.27mm_Vertical"
footprint_filters = ["Connector*:*_2x??_*"]
pin_names = "hidden"
pin_name_offset = 1.016

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, -6.35]
end = [3.81, 6.35]
width = 0.254
fill = "background"

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, -5.207]
end = [0.0, -4.953]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, -2.667]
end = [0.0, -2.413]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, -0.127]
end = [0.0, 0.127]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, 2.413]
end = [0.0, 2.667]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [-1.27, 4.953]
end = [0.0, 5.207]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [3.81, -5.207]
end = [2.54, -4.953]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [3.81, -2.667]
end = [2.54, -2.413]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [3.81, -0.127]
end = [2.54, 0.127]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [3.81, 2.413]
end = [2.54, 2.667]
width = 0.1524

[[graphics]]
kind = "rect"
unit = 1
start = [3.81, 4.953]
end = [2.54, 5.207]
width = 0.1524

[[pins]]
number = "1"
name = "Pin_1"
type = "passive"
at = [-5.08, -5.08]
side = "left"
length = 3.81
unit = 1

[[pins]]
number = "3"
name = "Pin_3"
type = "passive"
at = [-5.08, -2.54]
side = "left"
length = 3.81
unit = 1

[[pins]]
number = "5"
name = "Pin_5"
type = "passive"
at = [-5.08, 0.0]
side = "left"
length = 3.81
unit = 1

[[pins]]
number = "7"
name = "Pin_7"
type = "passive"
at = [-5.08, 2.54]
side = "left"
length = 3.81
unit = 1

[[pins]]
number = "9"
name = "Pin_9"
type = "passive"
at = [-5.08, 5.08]
side = "left"
length = 3.81
unit = 1

[[pins]]
number = "2"
name = "Pin_2"
type = "passive"
at = [7.62, -5.08]
side = "right"
length = 3.81
unit = 1

[[pins]]
number = "4"
name = "Pin_4"
type = "passive"
at = [7.62, -2.54]
side = "right"
length = 3.81
unit = 1

[[pins]]
number = "6"
name = "Pin_6"
type = "passive"
at = [7.62, 0.0]
side = "right"
length = 3.81
unit = 1

[[pins]]
number = "8"
name = "Pin_8"
type = "passive"
at = [7.62, 2.54]
side = "right"
length = 3.81
unit = 1

[[pins]]
number = "10"
name = "Pin_10"
type = "passive"
at = [7.62, 5.08]
side = "right"
length = 3.81
unit = 1
