# imported from KiCad 74xGxx:74LVC1G06
name = "74LVC1G06"
reference = "U"
description = "Single NOT Gate, Open Drain, Low-Voltage CMOS"
footprint = "SOT-353_SC-70-5"
datasheet = "http://www.ti.com/lit/sg/scyt129e/scyt129e.pdf"
keywords = ["Single", "Gate", "NOT", "LVC", "CMOS", "Open", "Drain"]
footprint_filters = ["SOT*", "SG-*"]

[[graphics]]
kind = "polygon"
points = [[-7.62, -6.35], [-7.62, 6.35], [5.08, 0.0]]
width = 0.254
fill = "background"

[[graphics]]
kind = "polyline"
points = [[-3.81, 1.27], [-1.27, 1.27]]
width = 0.254
fill = "background"

[[graphics]]
kind = "polygon"
points = [[-2.54, -1.27], [-3.81, 0.0], [-2.54, 1.27], [-1.27, 0.0]]
width = 0.254
fill = "background"

[[pins]]
number = "2"
type = "input"
at = [-15.24, 0.0]
side = "left"
length = 7.62
unit = 1

[[pins]]
number = "5"
name = "VCC"
type = "power_in"
at = [-5.08, -10.16]
side = "top"
length = 5.08
unit = 1

[[pins]]
number = "3"
name = "GND"
type = "power_in"
at = [-5.08, 10.16]
side = "bottom"
length = 5.08
unit = 1

[[pins]]
number = "4"
type = "open_collector"
at = [12.7, 0.0]
side = "right"
length = 7.62
unit = 1
shape = "inverted"

[[pins]]
number = "1"
name = "NC"
type = "free"
at = [-2.54, 10.16]
side = "bottom"
length = 6.35
unit = 1
