# imported from KiCad /tmp/hackrf-pro/praline.kicad_pcb
name = "Anaren_0805_2012Metric-6"
description = "https://cdn.anaren.com/product-documents/Xinger/DirectionalCouplers/DC4759J5020AHF/DC4759J5020AHF_DataSheet(Rev_E).pdf"
tags = ["coupler", "rf"]
mount = "smd"
model = "${KICAD9_3DMODEL_DIR}/RF_Converter.3dshapes/Balun_Johanson_0896BM15A0001.step"

[[pads]]
number = "1"
kind = "smd"
shape = "rect"
at = [-0.495, -0.65]
size = [0.41, 0.33]
rotation = -90.0
layers = ["F.Cu", "F.Mask", "F.Paste"]
count = 3
pitch = [0.0, 0.65]

[[pads]]
number = "4"
kind = "smd"
shape = "rect"
at = [0.495, 0.65]
size = [0.41, 0.33]
rotation = -90.0
layers = ["F.Cu", "F.Mask", "F.Paste"]
count = 3
pitch = [0.0, -0.65]

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-0.005, -1.12]
end = [0.64, -1.12]
width = 0.12

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-0.65, 1.12]
end = [0.64, 1.12]
width = 0.12

[[graphics]]
kind = "polygon"
layer = "F.SilkS"
points = [[-0.76, -1.12], [-1.04, -1.12], [-0.76, -1.4], [-0.76, -1.12]]
width = 0.12
fill = "solid"

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [0.91, 1.27]
end = [-0.91, 1.27]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [0.91, -1.27]
end = [0.91, 1.27]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-0.91, 1.27]
end = [-0.91, -1.27]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-0.91, -1.27]
end = [0.91, -1.27]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.645, 1.02]
end = [0.645, -1.02]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.645, -1.02]
end = [-0.3225, -1.02]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.645, 1.02]
end = [0.645, 1.02]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.645, -0.6975]
end = [-0.3225, -1.02]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.645, -0.6975]
end = [-0.645, 1.02]
width = 0.1

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.0, 0.0]
text = "${REFERENCE}"
size = 0.5
rotation = 90.0
