# imported from KiCad /tmp/hackrf-pro/praline.kicad_pcb
name = "L_Taiyo-Yuden_NR-40xx"
description = "Inductor, Taiyo Yuden, NR series, Taiyo-Yuden_NR-40xx, 4.0mmx4.0mm"
tags = ["inductor", "taiyo-yuden", "nr", "smd"]
mount = "smd"
model = "3dmodels/L_XND4040TK.STEP"

[[pads]]
number = "1"
kind = "smd"
shape = "rect"
at = [-1.4, 0.0]
size = [1.2, 3.7]
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[pads]]
number = "2"
kind = "smd"
shape = "rect"
at = [1.4, 0.0]
size = [1.2, 3.7]
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-2.0, 2.1]
end = [2.0, 2.1]
width = 0.12

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-2.0, -2.1]
end = [2.0, -2.1]
width = 0.12

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [2.25, 2.25]
end = [2.25, -2.25]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [2.25, -2.25]
end = [-2.25, -2.25]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-2.25, 2.25]
end = [2.25, 2.25]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-2.25, -2.25]
end = [-2.25, 2.25]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [2.0, 1.25]
end = [1.25, 2.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [2.0, -1.25]
end = [2.0, 1.25]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [2.0, -1.25]
end = [1.25, -2.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-1.25, 2.0]
end = [1.25, 2.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-1.25, -2.0]
end = [1.25, -2.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-2.0, 1.25]
end = [-1.25, 2.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-2.0, 1.25]
end = [-2.0, -1.25]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-2.0, -1.25]
end = [-1.25, -2.0]
width = 0.1

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.0, 0.0]
text = "${REFERENCE}"
size = 1.0
