# imported from KiCad /tmp/hackrf-pro/praline.kicad_pcb
name = "TestPoint_Loop_D1.80mm_Drill1.0mm_Beaded"
description = "wire loop with bead as test point, loop diameter 1.8mm, hole diameter 1.0mm"
tags = ["test", "point", "wire", "loop", "bead"]
mount = "tht"
model = "${KICAD9_3DMODEL_DIR}/TestPoint.3dshapes/TestPoint_Loop_D1.80mm_Drill1.0mm_Beaded.step"

[[pads]]
number = "1"
kind = "tht"
shape = "circle"
at = [0.0, 0.0]
size = [2.0, 2.0]
drill = 1.0
layers = ["*.Cu", "*.Mask"]

[[graphics]]
kind = "circle"
layer = "F.SilkS"
center = [0.0, 0.0]
radius = 1.5
width = 0.12

[[graphics]]
kind = "circle"
layer = "F.CrtYd"
center = [0.0, 0.0]
radius = 1.8
width = 0.05

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.9, -0.2]
end = [0.9, -0.2]
width = 0.12

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.9, 0.2]
end = [-0.9, -0.2]
width = 0.12

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.9, -0.2]
end = [0.9, 0.2]
width = 0.12

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.9, 0.2]
end = [-0.9, 0.2]
width = 0.12

[[graphics]]
kind = "circle"
layer = "F.Fab"
center = [0.0, 0.0]
radius = 1.3
width = 0.12

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.7, 2.5]
text = "${REFERENCE}"
size = 1.0
