# imported from KiCad Diode_SMD:D_SOD-323
name = "D_SOD-323"
description = "SOD-323"
tags = ["SOD-323"]
mount = "smd"
model = "${KICAD9_3DMODEL_DIR}/Diode_SMD.3dshapes/D_SOD-323.step"

[[pads]]
number = "1"
kind = "smd"
shape = "roundrect"
at = [-1.05, 0.0]
size = [0.6, 0.45]
roundrect_ratio = 0.25
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[pads]]
number = "2"
kind = "smd"
shape = "roundrect"
at = [1.05, 0.0]
size = [0.6, 0.45]
roundrect_ratio = 0.25
layers = ["F.Cu", "F.Mask", "F.Paste"]

[[graphics]]
kind = "text"
layer = "F.SilkS"
at = [0.0, -1.85]
text = "${REFERENCE}"
size = 1.0

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.1, 1.9]
text = "${VALUE}"
size = 1.0

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-1.61, -0.85]
end = [-1.61, 0.85]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-1.61, -0.85]
end = [1.05, -0.85]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.SilkS"
start = [-1.61, 0.85]
end = [1.05, 0.85]
width = 0.15

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-1.6, -0.95]
end = [-1.6, 0.95]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-1.6, -0.95]
end = [1.6, -0.95]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [-1.6, 0.95]
end = [1.6, 0.95]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.CrtYd"
start = [1.6, -0.95]
end = [1.6, 0.95]
width = 0.05

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.9, -0.7]
end = [0.9, -0.7]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.9, 0.7]
end = [-0.9, -0.7]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.3, -0.35]
end = [-0.3, 0.35]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.3, 0.0]
end = [-0.5, 0.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [-0.3, 0.0]
end = [0.2, -0.35]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.2, -0.35]
end = [0.2, 0.35]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.2, 0.0]
end = [0.45, 0.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.2, 0.35]
end = [-0.3, 0.0]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.9, -0.7]
end = [0.9, 0.7]
width = 0.1

[[graphics]]
kind = "line"
layer = "F.Fab"
start = [0.9, 0.7]
end = [-0.9, 0.7]
width = 0.1

[[graphics]]
kind = "text"
layer = "F.Fab"
at = [0.0, -1.85]
text = "${REFERENCE}"
size = 1.0
